### ISSUE TITLE
Broken Link in README.md - Documents - Manual

### ISSUE THREAD

**Issue by Yang09701194** [go-xorm/manual-en-US#13]
I find in [README.md](https://github.com/go-xorm/manual-en-US/blob/master/README.md), the **Manual** link in **Document** section (http://xorm.io/manual) bring me to *404 Not Found*, 

Hope it can be fixed, thanks!

![image](https://user-images.githubusercontent.com/23180780/39563928-9dcf13f8-4ee4-11e8-95b6-467c8806d59d.png)

**Comment by appleboy** [comment]
fixed in #14
