### ISSUE TITLE
a typo in readme.md, ch1

### ISSUE THREAD

**Issue by jihuichoi** [go-xorm/manual-en-US#15]
We alos provide a EngineInterface to do that.
: alos -> also

**Comment by lunny** [comment]
Could you send a PR to fix that?

**Comment by jihuichoi** [comment]
I already forked this repository to translate. So I can't make another one.
https://github.com/jihuichoi/manual-ko-KR

Let me know how, then I will do it.

**Comment by lunny** [comment]
I'm afraid you cannot fork twice on the same account. I will fix that myself. Thanks!
