### ISSUE TITLE
Mapping issue: Id int64 auto mapping to auto increment primary key - no longer valid

### ISSUE THREAD

**Issue by gunnsth** [go-xorm/manual-en-US#17]
From: https://github.com/go-xorm/manual-en-US/blob/master/chapter-02/4.columns.mdi.	
```
If field is name of Id and type of int64, xorm makes it as auto increment primary key. If another field, use struct tag xorm:"pk".
```
Is this no longer valid?

Seems like it is not picking up `Id` anymore.  Should update the documentation.

**Comment by lunny** [comment]
It still valids.
